# Dockerfile for namegen-project
FROM node:boron

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN git clone https://github.com/redhat-developer-demos/namegen.git .

RUN npm install

COPY . .

EXPOSE 8080
CMD ["npm", "start"]
